/** Localized engineering workbench served by the authenticated Desktop Host. */
const english = {
  title:'Engineering workbench',workspace:'Workspace',browse:'Choose folder',refresh:'Refresh',environment:'Repository',review:'Changes and draft',builds:'Build and test',artifacts:'Files and artifacts',recovery:'Task status',protection:'Protected files',
  fullAccess:'Allow unrestricted file writes for this Git operation only',branch:'Branch',remote:'Remote',message:'Commit message',preview:'Preview',apply:'Confirm operation',switch:'Switch branch',create:'Create branch',commit:'Commit staged changes',push:'Push branch',compare:'Compare branch',
  baseline:'Baseline',capture:'Capture baseline',comparison:'Comparison',repository:'Repository',task:'Since baseline',before:'Before baseline',staged:'Staged',unstaged:'Unstaged',file:'File',patch:'Show diff',excerpt:'Select a diff excerpt below, then choose an open composer.',composers:'Find open composers',append:'Append selected excerpt',draft:'Target composer',
  config:'Project actions configuration',save:'Save configuration',trust:'Trust this configuration',revoke:'Revoke trust',run:'Run',cancel:'Cancel',log:'Log',notifications:'Notify when a run finishes',manual:'Register workspace-relative file',register:'Register',open:'Open',reveal:'Show in folder',saveAs:'Save as',
  session:'Session',sessions:'Load sessions',inspect:'Inspect',unknown:'An interrupted operation can have side effects. Inspect the workspace before starting another operation.',snapshots:'Load snapshots',restore:'Restore selected paths',paths:'Selected paths, one per line',empty:'No entries',confirm:'Review the displayed operation and confirm?',trusted:'Trusted',untrusted:'Review and trust required',declared:'Build declaration; not proof of a newly generated file',success:'Completed',error:'Operation was not confirmed',help:'Run under the current Harness execution policy. Restoring files requires a fresh preview and no active protected task.',
}
const chinese: typeof english = {
  title:'工程工作台',workspace:'工作区',browse:'选择目录',refresh:'刷新',environment:'仓库',review:'变更与草稿',builds:'构建与测试',artifacts:'文件与产物',recovery:'任务状态',protection:'文件保护',
  fullAccess:'仅本次 Git 操作不限制文件写入',branch:'分支',remote:'远程',message:'提交说明',preview:'预览',apply:'确认操作',switch:'切换分支',create:'创建分支',commit:'提交暂存区',push:'推送分支',compare:'比较分支',
  baseline:'基线',capture:'采集基线',comparison:'比较范围',repository:'仓库',task:'基线之后',before:'基线之前',staged:'暂存区',unstaged:'未暂存',file:'文件',patch:'查看差异',excerpt:'在下方差异中选中片段，再选择已打开的草稿。',composers:'查找已打开草稿',append:'追加选中片段',draft:'目标草稿',
  config:'项目动作配置',save:'保存配置',trust:'信任此配置',revoke:'撤销信任',run:'运行',cancel:'取消',log:'日志',notifications:'运行结束时通知',manual:'登记工作区相对文件',register:'登记',open:'打开',reveal:'定位',saveAs:'另存为',
  session:'会话',sessions:'加载会话',inspect:'检查',unknown:'中断的操作可能已有副作用。再次操作前请检查工作区。',snapshots:'加载快照',restore:'恢复选定文件',paths:'选定路径，每行一个',empty:'暂无记录',confirm:'请核对已显示的操作并确认。',trusted:'已信任',untrusted:'需要审阅并信任',declared:'构建声明，不代表本次新生成',success:'已完成',error:'操作结果未确认',help:'执行遵循当前 Harness 权限。恢复文件需要最新预览，且不能有活动的受保护任务。',
}

/** Render the engineering controls without embedding user paths or configuration.
 * @param zh - Whether to use the Chinese dictionary.
 * @returns Self-contained authenticated workbench document.
 */
export function workbenchHtml(zh: boolean): string {
  const t = zh ? chinese : english
  return String.raw`<!doctype html><html lang="${zh?'zh-CN':'en'}"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${t.title}</title>
<style>:root{font:14px/1.5 system-ui;color:#172b3a;background:#f5f7f9}*{box-sizing:border-box}body{margin:0}header{background:#fff;border-bottom:1px solid #dce3ea;padding:22px 30px;position:sticky;top:0;z-index:2}h1{font-size:23px;margin:0 0 14px}nav{display:flex;gap:7px;flex-wrap:wrap;margin-top:15px}button,select,input,textarea{font:inherit;border:1px solid #bac8d3;border-radius:7px;padding:8px;background:#fff;color:inherit}button{cursor:pointer}button:hover{background:#e9f0f8}button:disabled{opacity:.45;cursor:default}nav button.active,.primary{background:#165c83;color:white}input:not([type=checkbox]){min-width:0;max-width:100%}input[type=checkbox]{width:auto;margin:0 6px 0 0}select{max-width:100%}label{max-width:100%}.row>*{min-width:0;max-width:100%}.item{overflow-wrap:anywhere}@media(max-width:650px){header{position:static;padding:16px}main{padding:0 12px;margin:12px auto}section{padding:14px}.row label{width:100%}}#workspace{flex:1}.row{display:flex;align-items:center;gap:9px;flex-wrap:wrap}.grow{flex:1}main{max-width:1200px;margin:24px auto;padding:0 24px}section{display:none;background:white;border:1px solid #dce3ea;border-radius:12px;padding:24px}section.active{display:block}label{display:block;margin:10px 0 5px}textarea{width:100%;resize:vertical;font-family:Consolas,monospace}pre{font:13px/1.6 Consolas,monospace;white-space:pre-wrap;overflow-wrap:anywhere;background:#f4f7fa;padding:14px;border-radius:8px;max-height:360px;overflow:auto}.item{border-bottom:1px solid #e1e8ee;padding:12px 0}.muted{color:#596b79}#notice{white-space:pre-wrap;min-height:24px;padding:0 30px;color:#a73829}small{display:block;color:#627485}#patch{height:290px}#config{height:260px}h2{margin-top:0;font-size:19px}</style>
<header><h1>${t.title}</h1><div class="row"><label for="workspace">${t.workspace}</label><input id="workspace" spellcheck="false"><button id="browse">${t.browse}</button><button id="refresh">${t.refresh}</button></div><nav>${['environment','review','builds','artifacts','recovery','protection'].map((key,index)=>`<button data-tab="${key}" class="${index===0?'active':''}">${t[key as keyof typeof t]}</button>`).join('')}</nav></header><div id="notice" role="status"></div><main>
<section id="environment" class="active"><h2>${t.environment}</h2><pre id="repoInfo"></pre><div class="row"><select id="gitAction">${['switch','create','commit','push'].map(key=>`<option value="${key}">${t[key as keyof typeof t]}</option>`).join('')}</select><label>${t.branch} <input id="branch" list="branches"></label><datalist id="branches"></datalist><label>${t.remote} <input id="remote" value="origin"></label><button id="compare">${t.compare}</button></div><label>${t.message}</label><textarea id="message" rows="2"></textarea><div class="row"><label><input type="checkbox" id="gitFullAccess"> ${t.fullAccess}</label><button id="gitPreview">${t.preview}</button><button id="gitApply" disabled>${t.apply}</button></div><pre id="gitResult"></pre></section>
<section id="review"><h2>${t.review}</h2><div class="row"><label>${t.baseline} <select id="baseline"><option value="">—</option></select></label><button id="capture">${t.capture}</button><select id="mode">${['repository','task','before','staged','unstaged'].map(key=>`<option value="${key}">${t[key as keyof typeof t]}</option>`).join('')}</select><button id="changes">${t.refresh}</button></div><div id="changesList"></div><label>${t.file} <input id="file"></label><button id="showPatch">${t.patch}</button><p>${t.excerpt}</p><textarea id="patch" readonly></textarea><div class="row"><button id="composers">${t.composers}</button><select id="composer" aria-label="${t.draft}"></select><button id="append">${t.append}</button></div><pre id="draftResult"></pre></section>
<section id="builds"><h2>${t.builds}</h2><small>${t.help}</small><label>${t.config}</label><textarea id="config" spellcheck="false"></textarea><div class="row"><button id="saveConfig">${t.save}</button><button id="trust">${t.trust}</button><button id="revoke">${t.revoke}</button><strong id="trusted"></strong></div><label><input type="checkbox" id="notifications"> ${t.notifications}</label><div id="actionList"></div><div id="runs"></div><pre id="runLog"></pre></section>
<section id="artifacts"><h2>${t.artifacts}</h2><div class="row"><input id="artifactPath" class="grow" placeholder="${t.manual}"><button id="register">${t.register}</button><button id="loadArtifacts">${t.refresh}</button></div><label>${t.session} <input id="artifactSession" placeholder="Session ID"></label><div id="artifactList"></div></section>
<section id="recovery"><h2>${t.recovery}</h2><p class="muted">${t.unknown}</p><button id="sessions">${t.sessions}</button><select id="session" aria-label="${t.session}"></select><button id="inspectRecovery">${t.inspect}</button><pre id="recoveryResult"></pre></section>
<section id="protection"><h2>${t.protection}</h2><p>${t.help}</p><button id="snapshots">${t.snapshots}</button><select id="snapshot"></select><button id="restorePreview">${t.preview}</button><pre id="restoreResult"></pre><label>${t.paths}</label><textarea id="restorePaths" rows="4"></textarea><button id="restore">${t.restore}</button></section></main>
<script>const t=${JSON.stringify(t)};const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let tab='environment',gitTicket,actionView,patchValue,restoreValue;const clients=new Map(),observedRuns=new Map();const drafts=new BroadcastChannel('nidofy-workbench-drafts');
const show=(id,value)=>$(id).textContent=typeof value==='string'?value:JSON.stringify(value,null,2);const busy=fn=>async()=>{try{$('notice').textContent='';await fn()}catch(e){$('notice').textContent=t.error+': '+e.message}};
async function api(method,data={}){const r=await fetch('/api/nidofy/workbench/'+method,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({workspace:$('workspace').value,...data})});const value=await r.json();if(!r.ok)throw Error((value.error||t.error)+(value.detail?' '+JSON.stringify(value.detail):''));return value}
async function protect(data){const r=await fetch('/api/nidofy/protection',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)});const v=await r.json();if(!r.ok)throw Error(v.error);return v}
function on(id,fn){$(id).onclick=busy(fn)}
document.querySelectorAll('[data-tab]').forEach(button=>button.onclick=busy(async()=>{tab=button.dataset.tab;document.querySelectorAll('section,nav button').forEach(el=>el.classList.toggle('active',el.id===tab||el.dataset.tab===tab));await refresh()}));
async function refresh(){localStorage.setItem('nidofy.workbench.workspace',$('workspace').value);gitTicket=null;$('gitApply').disabled=true;if(tab==='environment'){const v=await api('environment');show('repoInfo',v);$('branches').innerHTML=(v.branches||[]).map(b=>'<option value="'+esc(b)+'">').join('')}if(tab==='review')await changes();if(tab==='builds')await actions(true);if(tab==='artifacts')await artifacts();if(tab==='recovery')await sessions();if(tab==='protection')await snapshots()}
on('browse',async()=>{const root=await window.__DSH_DIRECTORY_PICKER__.pick();if(root){$('workspace').value=root;await refresh()}});on('refresh',refresh);
on('gitPreview',async()=>{gitTicket=await api('git/preview',{operation:{fullAccess:$('gitFullAccess').checked,action:$('gitAction').value,branch:$('branch').value,remote:$('remote').value,message:$('message').value}});show('gitResult',gitTicket);$('gitApply').disabled=false});
on('gitApply',async()=>{if(!gitTicket||!confirm(t.confirm))return;const ticket=gitTicket;gitTicket=null;$('gitApply').disabled=true;show('gitResult',await api('git/apply',{token:ticket.token}));await refresh()});on('compare',async()=>show('gitResult',await api('compare',{branch:$('branch').value})));
async function changes(){const baselines=await api('review/list');const list=baselines.items;if(baselines.unavailable?.length)show('notice',baselines.unavailable);const selected=$('baseline').value;$('baseline').innerHTML='<option value="">—</option>'+list.map(row=>'<option value="'+esc(row.id)+'">'+esc(new Date(row.createdAt).toLocaleString()+' '+row.source)+'</option>').join('');$('baseline').value=selected;const v=await api('review/changes',{baselineId:$('baseline').value});$('changesList').innerHTML=v.rows.map(row=>'<div class="item"><button data-path="'+esc(row.path)+'">'+esc(row.path)+'</button> '+esc(row.status+' '+row.classification)+'</div>').join('');$('changesList').querySelectorAll('button').forEach(b=>b.onclick=()=>{$('file').value=b.dataset.path})}
$('baseline').onchange=busy(async()=>{patchValue=null;$('patch').value='';await changes()});$('mode').onchange=()=>{patchValue=null;$('patch').value=''};on('changes',changes);on('capture',async()=>{await api('review/capture');await changes()});on('showPatch',async()=>{patchValue=await api('review/patch',{path:$('file').value,mode:$('mode').value,baselineId:$('baseline').value});$('patch').value=patchValue.text||patchValue.reason||''});
drafts.onmessage=event=>{const v=event.data;if(v.type==='composer'){clients.set(v.clientId,v);$('composer').innerHTML=[...clients.values()].map(c=>'<option value="'+esc(c.clientId)+'">'+esc(c.sessionId+' · '+c.phase+' · '+c.attachmentCount)+'</option>').join('')}if(v.type==='receipt')show('draftResult',v)};
on('composers',async()=>{clients.clear();$('composer').innerHTML='';drafts.postMessage({type:'discover',nonce:crypto.randomUUID()})});on('append',async()=>{const c=clients.get($('composer').value);if(!c||!patchValue)throw Error('DRAFT_TARGET_REQUIRED');const value=await api('draft/stage',{sessionId:c.sessionId,clientId:c.clientId,revision:c.revision,path:patchValue.path,mode:patchValue.mode,baselineId:$('baseline').value,hash:patchValue.hash,start:$('patch').selectionStart,end:$('patch').selectionEnd});show('draftResult',value);drafts.postMessage({type:'append',ticket:value.ticket,sessionId:c.sessionId,clientId:c.clientId});setTimeout(()=>busy(async()=>show('draftResult',await api('draft/status',{ticket:value.ticket})))(),12000)});
async function actions(config){actionView=await api('actions/inspect');if(config)$('config').value=JSON.stringify(actionView.config,null,2);$('trusted').textContent=actionView.trusted?t.trusted:t.untrusted;$('actionList').innerHTML=actionView.config.actions.map(a=>'<div class="item"><b>'+esc(a.label)+'</b> <button data-run="'+esc(a.id)+'">'+t.run+'</button><pre>'+esc(a.command)+'</pre></div>').join('');$('actionList').querySelectorAll('button').forEach(b=>b.onclick=busy(async()=>{await api('actions/start',{id:b.dataset.run});await actions(false)}));$('runs').innerHTML=actionView.runs.map(r=>'<div class="item">'+esc(r.label+' · '+r.status)+' <button data-cancel="'+esc(r.id)+'">'+t.cancel+'</button> <button data-log="'+esc(r.id)+'">'+t.log+'</button><small>'+esc(r.message||'')+'</small></div>').join('');$('runs').querySelectorAll('[data-cancel]').forEach(b=>b.onclick=busy(async()=>{await api('actions/cancel',{id:b.dataset.cancel});await actions(false)}));$('runs').querySelectorAll('[data-log]').forEach(b=>b.onclick=busy(async()=>show('runLog',(await api('actions/log',{id:b.dataset.log})).text)));for(const run of actionView.runs){const prior=observedRuns.get(run.id);if(prior&&['RUNNING','QUEUED'].includes(prior)&&!['RUNNING','QUEUED'].includes(run.status)&&$('notifications').checked)window.nidofyWorkbench?.notify(run.label,run.status);observedRuns.set(run.id,run.status)}}
$('notifications').onchange=busy(()=>window.nidofyWorkbench.notifications($('notifications').checked));on('saveConfig',async()=>{await api('actions/save',{config:JSON.parse($('config').value)});await actions(true)});on('trust',async()=>{if(actionView&&confirm(t.confirm)){await api('actions/trust',{fingerprint:actionView.fingerprint});await actions(false)}});on('revoke',async()=>{await api('actions/revoke');await actions(false)});
async function artifacts(){const rows=await api('artifacts/list',{sessionId:$('artifactSession').value});$('artifactList').innerHTML=rows.map(row=>'<div class="item"><b>'+esc(row.path)+'</b><small>'+esc(row.source==='build-declared'?t.declared:row.source)+'</small><small>'+esc(row.runStatus||'')+'</small>'+['open','reveal','save'].map(action=>'<button data-id="'+esc(row.id||'')+'" data-action="'+action+'" '+(!row.available||(action==='open'&&!row.canOpen)||(action==='save'&&!row.canSave)?'disabled':'')+'>'+t[action==='save'?'saveAs':action]+'</button>').join(' ')+'</div>').join('');$('artifactList').querySelectorAll('button').forEach(b=>b.onclick=busy(async()=>show('notice',await window.nidofyWorkbench.artifact(b.dataset.id,b.dataset.action))))}
on('loadArtifacts',artifacts);on('register',async()=>{await api('artifacts/register',{path:$('artifactPath').value});await artifacts()});
async function sessions(){const rows=await api('sessions');$('session').innerHTML=rows.map(r=>'<option value="'+esc(r.id)+'">'+esc(r.id+' · '+(r.workspace||''))+'</option>').join('')};on('sessions',sessions);on('inspectRecovery',async()=>show('recoveryResult',await api('recovery',{sessionId:$('session').value})));
async function snapshots(){const value=await protect({action:'list'});const rows=Array.isArray(value)?value:value.items||value.snapshots||[];$('snapshot').innerHTML=rows.map(row=>'<option value="'+esc(row.id)+'">'+esc(row.id+' '+(row.status||''))+'</option>').join('')};on('snapshots',snapshots);on('restorePreview',async()=>{restoreValue=await protect({action:'preview',id:$('snapshot').value});show('restoreResult',restoreValue);$('restorePaths').value=(restoreValue.rows||[]).filter(r=>r.status==='READY').map(r=>r.path).join('\n')});on('restore',async()=>{if(!restoreValue||!confirm(t.confirm))return;const value=restoreValue;restoreValue=null;show('restoreResult',await protect({action:'restore',id:$('snapshot').value,expectedRevision:value.revision,paths:$('restorePaths').value.split(/\r?\n/).filter(Boolean)}))});
const params=new URLSearchParams(location.search);$('workspace').value=params.get('workspace')||localStorage.getItem('nidofy.workbench.workspace')||'';const initial=params.get('tab');if(['environment','review','builds','artifacts','recovery','protection'].includes(initial)){tab=initial;document.querySelectorAll('section,nav button').forEach(el=>el.classList.toggle('active',el.id===tab||el.dataset.tab===tab));}setInterval(()=>{if(actionView&&actionView.runs.some(r=>['RUNNING','QUEUED'].includes(r.status)))void busy(()=>actions(false))()},2000);window.addEventListener('pagehide',()=>drafts.close());if($('workspace').value)void busy(refresh)();
</script></html>`
}
