/** Local optional-capability dashboard; all mutations use the authenticated Host and revision checks. */
export function extrasHtml(zh: boolean): string {
  const labels = zh ? {
    title: '个人扩展', intro: '按需启用，本地保存。关闭扩展不影响连接、工程任务和文件保护。', diagnostics: '诊断与对比', cache: '缓存实验', vision: '独立识图', pets: '桌宠', schedule: '自动化迁移', selftest: '本地自检',
    showPet: '显示桌宠', hidePets: '隐藏所有桌宠', enablePets: '启用桌宠服务（总开关）', enable: '启用', save: '保存设置', refresh: '刷新', export: '导出脱敏报告', archive: '归档当前报告', compare: '比较两份归档', clear: '清空观测',
    provider: '连接', model: '模型', budget: '合成输入估算 tokens', requests: '请求次数', consent: '确认发送合成内容；可能产生模型费用', start: '开始实验', cancel: '取消',
    cacheHint: '估算采用字符数 ÷ 4；字节数另行显示。计数缺失或响应更快不能证明缓存命中。实验不读取会话内容。', mode: '缓存路由键', models: '仅用于这些模型（逗号分隔）',
    path: '本地文件路径', question: '图片问题', analyze: '分析图片', imageConsent: '确认将这一张图片和问题发送到所选连接',
    petHint: '保留原有动画、点击互动、观察方向、拖动、固定会话与状态提示。资源只从本地导入。', scale: '大小', interaction: '点击互动', look: '观察方向', quiet: '安静模式', resource: '资源 ID', preview: '预检资源包', install: '导入已预检资源', remove: '删除自定义资源', replace: '替换同 ID 资源', exportPet: '导出所选资源 ZIP', destination: '导出目录', instance:'实例（最多三个）', addPet:'添加实例', removePet:'移除实例', activePet:'显示这个实例', mood:'本地互动心情', bubbleTheme:'气泡主题', bubblePlace:'气泡位置', bubbleFont:'气泡字号', bubbleDuration:'气泡时长（毫秒）', templates:'气泡模板 JSON',
    scheduleHint: '在主窗口「插件 → 官方 → 自动化任务」启用预置插件，无需下载。旧计划导入后保持暂停；逐项选择会话和新的未来时间恢复，不补跑积压任务。', import: '导入计划清单', restore: '确认恢复所选计划', session: '目标会话 ID', interval: '新的重复间隔（秒，至少 60）',
    theme: '主题与字体使用主窗口「设置 → 通用 → 外观」。', inspect: '运行本地检查（不访问模型）', migration: '旧实验单位检查', archiveA: '归档 A', archiveB: '归档 B', ready: '准备就绪',
  } : {
    title: 'Personal extensions', intro: 'Enable only what you use. Local preferences; disabling extensions leaves connections, workbench and protection available.', diagnostics: 'Diagnostics', cache: 'Cache experiments', vision: 'Vision connection', pets: 'Desktop pet', schedule: 'Schedule migration', selftest: 'Local checks',
    showPet: 'Show pet', hidePets: 'Hide all pets', enablePets: 'Enable desktop pets (master switch)', enable: 'Enable', save: 'Save settings', refresh: 'Refresh', export: 'Export redacted report', archive: 'Archive report', compare: 'Compare archives', clear: 'Clear observations',
    provider: 'Connection', model: 'Model', budget: 'Estimated synthetic input tokens', requests: 'Requests', consent: 'Send synthetic content; model charges may apply', start: 'Run experiment', cancel: 'Cancel',
    cacheHint: 'Estimates use characters ÷ 4; bytes are recorded separately. Missing counters or lower latency do not prove cache hits. Experiments never read conversation content.', mode: 'Cache routing key', models: 'Only these model IDs (comma separated)',
    path: 'Local file path', question: 'Image question', analyze: 'Analyze image', imageConsent: 'Send this image and question to the selected connection',
    petHint: 'Original animation, interaction, gaze, dragging, session pinning and state notices. Resource imports stay local.', scale: 'Scale', interaction: 'Click interactions', look: 'Gaze tracking', quiet: 'Quiet mode', resource: 'Resource ID', preview: 'Preview resource', install: 'Import reviewed resource', remove: 'Delete custom resource', replace: 'Replace the same resource ID', exportPet: 'Export selected resource ZIP', destination: 'Export directory', instance:'Instance (up to three)', addPet:'Add instance', removePet:'Remove instance', activePet:'Show this instance', mood:'Local interaction mood', bubbleTheme:'Bubble theme', bubblePlace:'Bubble placement', bubbleFont:'Bubble font size', bubbleDuration:'Bubble duration (ms)', templates:'Bubble templates JSON',
    scheduleHint: 'Enable the bundled Automation tasks plugin in the main window under Plugins → Official. No download is needed. Imported plans stay paused; restore each to a selected session with a new future rule. Missed occurrences never replay.', import: 'Import plan manifest', restore: 'Confirm selected plan', session: 'Target session ID', interval: 'New repeat interval (seconds, at least 60)',
    theme: 'Use Settings → General → Appearance in the main window for theme and font size.', inspect: 'Run local checks (no model requests)', migration: 'Check legacy experiment units', archiveA: 'Archive A', archiveB: 'Archive B', ready: 'Ready',
  }
  return String.raw`<!doctype html><html lang="${zh ? 'zh-CN' : 'en'}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${labels.title}</title><style>
  :root{color-scheme:light dark;--bg:#f6f8fb;--card:#fff;--fg:#17233c;--muted:#55647b;--line:#dce2ee;--accent:#315fc4}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--fg);font:14px/1.6 system-ui,'Microsoft YaHei',sans-serif}main{max-width:1080px;margin:auto;padding:30px}h1{font-size:28px;margin:0}p{color:var(--muted)}nav{display:flex;gap:8px;flex-wrap:wrap;margin:24px 0}button,select,input,textarea{font:inherit}button{border:1px solid var(--line);background:var(--card);color:var(--fg);padding:8px 14px;border-radius:8px;cursor:pointer}button.primary,nav button[aria-selected=true]{background:var(--accent);color:white;border-color:var(--accent)}button:disabled{opacity:.45;cursor:default}section{background:var(--card);border:1px solid var(--line);border-radius:14px;padding:22px;margin-bottom:18px}section[hidden]{display:none}h2{font-size:19px;margin:0 0 14px}.row{display:flex;align-items:flex-end;gap:12px;flex-wrap:wrap;margin:12px 0}label{max-width:100%;min-inline-size:0;display:grid;gap:5px;min-width:min(180px,100%);color:var(--muted)}label.check{display:flex;align-items:center;min-width:0}input:not([type=checkbox]),select,textarea{width:100%;border:1px solid var(--line);border-radius:7px;background:var(--bg);color:var(--fg);padding:8px}textarea{min-height:80px}input[type=checkbox]{accent-color:var(--accent)}.grow{flex:1;min-width:min(240px,100%)}#status{margin:16px 0;background:var(--card);border:1px solid var(--line);padding:10px 16px;border-radius:9px;overflow-wrap:anywhere}pre{background:var(--bg);padding:14px;border-radius:8px;max-width:100%;max-height:350px;overflow:auto;white-space:pre-wrap;overflow-wrap:anywhere}#records{overflow-x:auto}table{border-collapse:collapse;width:100%;font-size:13px}th,td{text-align:left;border-bottom:1px solid var(--line);padding:9px;overflow-wrap:anywhere}.metric{background:var(--bg);padding:10px 14px;border-radius:8px}#petpreview{max-width:192px;max-height:208px;object-fit:contain}small{color:var(--muted)}@media(prefers-color-scheme:dark){:root{--bg:#111a2a;--card:#1c283d;--fg:#e7edf7;--muted:#aebbd0;--line:#38455d;--accent:#507cdc}}@media(max-width:600px){main{padding:16px}section{padding:15px}.row>*{max-width:100%}.row>.grow{flex-basis:100%}}
  </style></head><body><main><h1>${labels.title}</h1><p>${labels.intro}</p><nav>${['diagnostics','cache','vision','pets','schedule','selftest'].map(k => `<button data-tab="${k}" aria-selected="${k === 'diagnostics'}">${labels[k as keyof typeof labels]}</button>`).join('')}</nav>
  <section id="diagnostics"><h2>${labels.diagnostics}</h2><div class="row"><label class="check"><input type="checkbox" data-feature="diagnostics">${labels.enable}</label><button data-save>${labels.save}</button><button id="diagrefresh">${labels.refresh}</button><button id="archive">${labels.archive}</button><button id="export">${labels.export}</button><button id="clear">${labels.clear}</button></div><div id="metrics" class="row"></div><div id="records"></div><div class="row"><label class="grow">${labels.archiveA}<select id="archivea"></select></label><label class="grow">${labels.archiveB}<select id="archiveb"></select></label><button id="compare">${labels.compare}</button></div><pre id="comparison" hidden></pre></section>
  <section id="cache" hidden><h2>${labels.cache}</h2><p>${labels.cacheHint}</p><div class="row"><label class="check"><input type="checkbox" data-feature="cache">${labels.enable}</label><label>${labels.mode}<select id="cachemode"><option value="native">Native</option><option value="off">Off</option><option value="session">Session</option></select></label><label class="grow">${labels.models}<input id="cachemodels"></label><button data-save>${labels.save}</button></div><div class="row"><label>${labels.provider}<select id="provider"></select></label><label class="grow">${labels.model}<select id="model"></select></label></div><div class="row"><label>${labels.budget}<select id="budget"><option>512</option><option>2048</option><option>8192</option></select></label><label>${labels.requests}<select id="requests"><option>4</option><option>6</option></select></label></div><label class="check"><input id="consent" type="checkbox">${labels.consent}</label><div class="row"><button class="primary" id="probe">${labels.start}</button><button id="cancelprobe">${labels.cancel}</button><button id="probehistory">${labels.refresh}</button></div><pre id="proberesult"></pre><details><summary>${labels.migration}</summary><textarea id="legacybudget" placeholder='{"schemaVersion":1,"budget":{"inputBytes":8192}}'></textarea><button id="migratebudget">${labels.migration}</button><pre id="budgetresult"></pre></details></section>
  <section id="vision" hidden><h2>${labels.vision}</h2><div class="row"><label class="check"><input type="checkbox" data-feature="vision">${labels.enable}</label><label>${labels.provider}<select id="visionprovider"></select></label><label class="grow">${labels.model}<select id="visionmodel"></select></label><button data-save>${labels.save}</button></div><label>${labels.path}<input id="imagepath" placeholder="C:\Images\example.png"></label><div class="row"><input id="imagefile" type="file" accept="image/png,image/jpeg,image/webp,image/gif"></div><label>${labels.question}<textarea id="question"></textarea></label><div class="row"><label class="check"><input id="imageconsent" type="checkbox">${labels.imageConsent}</label><button class="primary" id="analyze">${labels.analyze}</button></div><pre id="visionresult"></pre></section>
  <section id="pets" hidden><h2>${labels.pets}</h2><div class="row"><button class="primary" id="showpet">${labels.showPet}</button><button id="hidepets">${labels.hidePets}</button></div><div class="row"><label class="grow">${labels.instance}<select id="petinstance"></select></label><button id="addinstance">${labels.addPet}</button><button id="removeinstance">${labels.removePet}</button></div><div class="row"><label class="check"><input id="petenabled" type="checkbox">${labels.activePet}</label><label class="check"><input id="petmood" type="checkbox">${labels.mood}</label></div><p>${labels.petHint}</p><div class="row"><label class="check"><input type="checkbox" data-feature="pets">${labels.enablePets}</label><label>${labels.scale}<select id="petscale"><option>0.75</option><option selected>1</option><option>1.25</option><option>1.5</option></select></label><label class="check"><input id="interaction" type="checkbox">${labels.interaction}</label><label class="check"><input id="look" type="checkbox">${labels.look}</label><label class="check"><input id="quiet" type="checkbox">${labels.quiet}</label></div><div class="row"><label class="grow">${labels.resource}<select id="petresource"></select></label><button data-save>${labels.save}</button><button id="deletepet">${labels.remove}</button></div><div class="row"><label>${labels.bubbleTheme}<select id="bubbletheme"><option>dark</option><option>light</option><option>blue</option></select></label><label>${labels.bubblePlace}<select id="bubbleplace"><option>top</option><option>bottom</option></select></label><label>${labels.bubbleFont}<input id="bubblefont" type="number" min="10" max="22"></label><label>${labels.bubbleDuration}<input id="bubbleduration" type="number" min="1000" max="15000"></label></div><label>${labels.templates}<input id="bubbletemplates"></label><label>${labels.path}<input id="petpath"></label><div class="row"><button id="previewpet">${labels.preview}</button><label class="check"><input id="replacepet" type="checkbox">${labels.replace}</label><button id="importpet" disabled>${labels.install}</button><img id="petpreview" alt=""></div><div class="row"><label class="grow">${labels.destination}<input id="petdestination"></label><button id="exportpet">${labels.exportPet}</button></div><pre id="petresult" hidden></pre></section>
  <section id="schedule" hidden><h2>${labels.schedule}</h2><p>${labels.scheduleHint}</p><label>${labels.path}<input id="schedulepath" placeholder="schedules.json"></label><div class="row"><button id="importschedule">${labels.import}</button><button id="refreshschedule">${labels.refresh}</button></div><label>${labels.schedule}<select id="paused"></select></label><pre id="schedulepreview"></pre><div class="row"><label class="grow">${labels.session}<input id="schedulesession"></label><label>${labels.interval}<input id="scheduleinterval" type="number" min="60" value="3600"></label><button id="restoreschedule">${labels.restore}</button></div><pre id="schedulestatus"></pre></section>
  <section id="selftest" hidden><h2>${labels.selftest}</h2><p>${labels.theme}</p><button id="selfcheck">${labels.inspect}</button><pre id="checks"></pre></section><div id="status" role="status">${labels.ready}</div><small>DSH 0.2.0-rc.2 · Nidofy M4 · local extensions</small></main><script>
  const $=id=>document.getElementById(id),out=(id,v)=>{$(id).hidden=false;$(id).textContent=typeof v==='string'?v:JSON.stringify(v,null,2)},rpc=async(method,input={})=>{const response=await fetch('/api/nidofy-extras/'+method,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(input)});const data=await response.json();if(!response.ok)throw Error(data.error);return data};let preferences,providers=[],plans=[],preview=null,closed=false;const action=fn=>async()=>{try{await fn();out('status','${labels.ready}')}catch(e){out('status',e.message)}},button=(id,fn)=>$(id).onclick=action(fn);
  document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('section').forEach(s=>s.hidden=s.id!==b.dataset.tab);document.querySelectorAll('[data-tab]').forEach(t=>t.setAttribute('aria-selected',String(t===b)))});
  const options=(id,items,selected)=>{const s=$(id);s.replaceChildren();for(const item of items){const o=document.createElement('option');o.value=item.value;o.textContent=item.label;s.append(o)}if(selected!==undefined)s.value=selected};
  function modelOptions(prefix){const p=$(prefix+'provider').value;options(prefix+'model',(providers.find(x=>x.provider===p)?.models??[]).map(x=>({value:x.id,label:x.name||x.id})),prefix==='vision'?preferences?.visionRoute.model:undefined)}
  async function load(){const s=await rpc('status');preferences=s.preferences;document.querySelectorAll('[data-feature]').forEach(x=>x.checked=preferences[x.dataset.feature]);$('cachemode').value=preferences.cachePolicy.mode;$('cachemodels').value=preferences.cachePolicy.models.join(',');$('petscale').value=preferences.pet.scale;for(const k of ['interaction','look','quiet'])$(k).checked=preferences.pet[k];providers=await rpc('models');for(const prefix of ['','vision']){options(prefix+'provider',providers.map(p=>({value:p.provider,label:p.provider})),prefix==='vision'?preferences.visionRoute.provider:undefined);modelOptions(prefix);$(prefix+'provider').onchange=()=>modelOptions(prefix)}instances();await pets();await diagnostics();if(s.warning)out('status',s.warning);else if(Object.values(s.features).includes('UNAVAILABLE'))out('status',s.features)}
  async function save(){const section=document.querySelector('section:not([hidden])').id,next=(await rpc('status')).preferences;const flag=document.querySelector('#'+section+' [data-feature]');if(flag)next[section]=flag.checked;if(section==='cache')next.cachePolicy={mode:$('cachemode').value,models:$('cachemodels').value.split(',').map(s=>s.trim()).filter(Boolean)};if(section==='vision')next.visionRoute={...next.visionRoute,provider:$('visionprovider').value,model:$('visionmodel').value};const p=[next.pet,...next.companions].find(p=>p.id===$('petinstance').value)||next.pet;if(section==='pets')Object.assign(p,{scale:Number($('petscale').value),resource:$('petresource').value||'xiaojing',enabled:$('petenabled').checked,moodEnabled:$('petmood').checked,interaction:$('interaction').checked,look:$('look').checked,quiet:$('quiet').checked,bubble:{theme:$('bubbletheme').value,placement:$('bubbleplace').value,fontSize:Number($('bubblefont').value),durationMs:Number($('bubbleduration').value),templates:JSON.parse($('bubbletemplates').value)}});preferences=await rpc('preferences',next)}
  document.querySelectorAll('[data-save]').forEach(b=>b.onclick=action(save));
  let latest;async function diagnostics(){latest=await rpc('diagnostics');$('metrics').replaceChildren();for(const [k,v]of Object.entries({requests:latest.records?.length??0,dropped:latest.dropped??0})){const span=document.createElement('span');span.className='metric';span.textContent=k+': '+v;$('metrics').append(span)}$('records').replaceChildren();const table=document.createElement('table');for(const row of [['Status','Purpose','Input tokens','Cache read','Duration ms'],...(latest.records??[]).slice(-20).map(r=>[r.status,r.purpose,r.usage?.inputTokens??'?',r.usage?.cacheReadTokens??'?',Math.round(r.durationMs??0)])]){const tr=document.createElement('tr');for(const v of row){const td=document.createElement('td');td.textContent=String(v);tr.append(td)}table.append(tr)}$('records').append(table);const archives=await rpc('diagnostics/list');for(const id of ['archivea','archiveb'])options(id,archives.map(a=>({value:a.id,label:a.id+' · '+a.requests})));}
  button('diagrefresh',diagnostics);button('archive',async()=>{await rpc('diagnostics/archive');await diagnostics()});button('clear',async()=>{await rpc('diagnostics/clear');await diagnostics()});button('compare',async()=>out('comparison',await rpc('diagnostics/compare',{a:$('archivea').value,b:$('archiveb').value})));button('export',async()=>{const blob=new Blob([JSON.stringify(await rpc('diagnostics'),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='dsh-diagnostics-redacted.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});
  button('probe',async()=>out('proberesult',await rpc('cache/start',{provider:$('provider').value,model:$('model').value,inputTokens:Number($('budget').value),requests:Number($('requests').value),accepted:$('consent').checked})));button('cancelprobe',()=>rpc('cache/cancel'));button('probehistory',async()=>out('proberesult',await rpc('cache/history')));button('migratebudget',async()=>out('budgetresult',await rpc('cache/migrate',JSON.parse($('legacybudget').value))));
  $('imagefile').onchange=()=>{const file=$('imagefile').files[0];if(file)$('imagepath').value=window.__DSH_HOST_PATHS__?.pathFor(file)||''};button('analyze',async()=>out('visionresult',await rpc('vision',{path:$('imagepath').value,question:$('question').value,accepted:$('imageconsent').checked})));
  button('showpet',async()=>{document.querySelector('[data-feature=pets]').checked=true;$('petenabled').checked=true;await save()});button('hidepets',async()=>{document.querySelector('[data-feature=pets]').checked=false;await save()});function selectedPet(){return [preferences.pet,...preferences.companions].find(p=>p.id===$('petinstance').value)||preferences.pet}function showPet(){const p=selectedPet();$('petscale').value=p.scale;for(const k of ['interaction','look','quiet'])$(k).checked=p[k];$('petenabled').checked=p.enabled;$('petmood').checked=p.moodEnabled;$('bubbletheme').value=p.bubble.theme;$('bubbleplace').value=p.bubble.placement;$('bubblefont').value=p.bubble.fontSize;$('bubbleduration').value=p.bubble.durationMs;$('bubbletemplates').value=JSON.stringify(p.bubble.templates);$('petresource').value=p.resource}function instances(id=$('petinstance').value){options('petinstance',[preferences.pet,...preferences.companions].map(p=>({value:p.id,label:p.id})),id||'1');showPet()}$('petinstance').onchange=showPet;button('addinstance',async()=>{preferences=(await rpc('status')).preferences;if(preferences.companions.length>=2)throw Error('PET_INSTANCE_LIMIT');const id=crypto.randomUUID().slice(0,8),p={...structuredClone(preferences.pet),id,position:null,pinned:null,enabled:true,affinity:0,lastInteractionMs:0};preferences=await rpc('preferences',{...preferences,pets:true,companions:[...preferences.companions,p]});document.querySelector('[data-feature=pets]').checked=true;instances(id);await pets()});button('removeinstance',async()=>{const id=$('petinstance').value;preferences=(await rpc('status')).preferences;if(id==='1')throw Error('PRIMARY_INSTANCE_REQUIRED');preferences=await rpc('preferences',{...preferences,companions:preferences.companions.filter(p=>p.id!==id)});instances('1');await pets()});
  async function pets(){const data=await rpc('pet/packages',{action:'list'});options('petresource',data.items.map(p=>({value:p.id,label:p.displayName})),selectedPet().resource)}button('previewpet',async()=>{preview=await rpc('pet/packages',{action:'preview',source:$('petpath').value});$('petpreview').src=preview.preview;$('importpet').disabled=false;out('petresult',{id:preview.id,warnings:preview.warnings,duplicate:preview.duplicate})});button('importpet',async()=>{if(!preview)throw Error('PREVIEW_REQUIRED');await rpc('pet/packages',{action:'import',source:$('petpath').value,expected:preview.digest,replace:$('replacepet').checked});$('importpet').disabled=true;preview=null;await pets()});button('deletepet',async()=>{if($('petresource').value==='xiaojing')throw Error('BUILTIN_RESOURCE_READ_ONLY');await rpc('pet/packages',{action:'delete',resourceId:$('petresource').value});await pets()});
  button('exportpet',async()=>out('petresult',await rpc('pet/packages',{action:'export',resourceId:$('petresource').value,destination:$('petdestination').value})));
  async function schedule(){const value=await rpc('schedule/list');plans=value.paused;options('paused',plans.map(p=>({value:p.id,label:p.status+' · '+p.title})));showPlan();out('schedulestatus',{enabled:value.enabled,officialTasks:value.official.length,paused:plans.length})}function showPlan(){out('schedulepreview',plans.find(p=>p.id===$('paused').value)??{})}$('paused').onchange=showPlan;button('refreshschedule',schedule);button('importschedule',async()=>{await rpc('schedule/import',{path:$('schedulepath').value});await schedule()});button('restoreschedule',async()=>{const plan=plans.find(p=>p.id===$('paused').value);if(!plan)throw Error('SELECT_PLAN');await rpc('schedule/restore',{id:plan.id,sessionId:$('schedulesession').value,accepted:true,request:{title:plan.title,prompt:plan.prompt,every_seconds:Number($('scheduleinterval').value)}});await schedule()});button('selfcheck',async()=>out('checks',await rpc('selftest')));
  const timer=setInterval(async()=>{if(closed)return;try{const state=await rpc('status');if(state.probe)out('proberesult',state.probe)}catch{}},2000);window.addEventListener('pagehide',()=>{closed=true;clearInterval(timer)});action(async()=>{await load();const tab=new URLSearchParams(location.search).get('tab');if(['diagnostics','cache','vision','pets','schedule','selftest'].includes(tab))document.querySelector('[data-tab='+tab+']').click()})();
  </script></body></html>`
}
